import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'remixicon/fonts/remixicon.css';
import { AuthProvider } from "./provider";
const inter = Inter({ subsets: ["latin"] });
import NextTopLoader from 'nextjs-toploader';
import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster richColors/>
        <NextTopLoader />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
